package io.github.orlouge.unruffled.utils;

import java.util.Map;

public class RomanNumerals {
    public static final Map<Integer, String> MAP = Map.ofEntries(
            Map.entry(1, "I"),
            Map.entry(2, "II"),
            Map.entry(3, "III"),
            Map.entry(4, "IV"),
            Map.entry(5, "V"),
            Map.entry(6, "VI"),
            Map.entry(7, "VII"),
            Map.entry(8, "VIII"),
            Map.entry(9, "IX"),
            Map.entry(10, "X"),
            Map.entry(11, "XI"),
            Map.entry(12, "XII"),
            Map.entry(13, "XIII"),
            Map.entry(14, "XIV"),
            Map.entry(15, "XV"),
            Map.entry(16, "XVI"),
            Map.entry(17, "XVII"),
            Map.entry(18, "XVIII"),
            Map.entry(19, "XIX"),
            Map.entry(20, "XX"),
            Map.entry(21, "XXI"),
            Map.entry(22, "XXII"),
            Map.entry(23, "XXIII"),
            Map.entry(24, "XXIV"),
            Map.entry(25, "XXV"),
            Map.entry(26, "XXVI"),
            Map.entry(27, "XXVII"),
            Map.entry(28, "XXVIII"),
            Map.entry(29, "XXIX"),
            Map.entry(30, "XXX"),
            Map.entry(31, "XXXI"),
            Map.entry(32, "XXXII"),
            Map.entry(33, "XXXIII"),
            Map.entry(34, "XXXIV"),
            Map.entry(35, "XXXV"),
            Map.entry(36, "XXXVI"),
            Map.entry(37, "XXXVII"),
            Map.entry(38, "XXXVIII"),
            Map.entry(39, "XXXIX"),
            Map.entry(40, "XL"),
            Map.entry(41, "XLI"),
            Map.entry(42, "XLII"),
            Map.entry(43, "XLIII"),
            Map.entry(44, "XLIV"),
            Map.entry(45, "XLV"),
            Map.entry(46, "XLVI"),
            Map.entry(47, "XLVII"),
            Map.entry(48, "XLVIII"),
            Map.entry(49, "XLIX"),
            Map.entry(50, "L")
    );
}
